### ISSUE TITLE
Set force-deletion flag when creating shoot-cluster [KIM/feature]

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/infrastructure-manager#103]
**Description**

Gardner supports now the option to [force the deletion of a cluster ](https://github.com/gardener/gardener/issues/3110#issuecomment-1705500823)(which avoids longer waiting-periods during the de-provisioning e.g.  the K8s cluster couldn't be gracefully stopped caused by hanging finalizers).

We agreed to use this feature flag and the infrastructure manager / provisioner should set this flag properly.

AC:
- [ ] The annotation `confirmation.gardener.cloud/force-deletion` is set in the shoot-specs of Gardener clusters.

**Reasons**

Enable/accept non-graceful shutdowns of Gardener clusters to avoid longer waiting periods during the de-provisioning.

**Attachments**
- https://gardener.cloud/docs/gardener/shoot_operations/#force-deletion

[Moved from Provisioner to KIM]

**Comment by tobiscr** [comment]
Pre-requisite for https://github.com/kyma-project/kyma/issues/18198

**Comment by Disper** [comment]
@tobiscr should that annotation be set for only new clusters or should also existing clusters be migrated at some point?

**Comment by Disper** [comment]
Aligned that we want to set it only for new clusters.

**Comment by Disper** [comment]
Added [relevant Gardener docu](https://gardener.cloud/docs/gardener/shoot_operations/#force-deletion) to the attachment list

**Comment by Disper** [comment]
According to [what I've tried](https://github.com/kyma-project/infrastructure-manager/pull/311#issuecomment-2252713497) - it's not possible to just create a cluster with that annotation set. 
> This is only possible if the Shoot fails to be deleted normally.

For more details, please refer to the [relevant Gardener docu](https://gardener.cloud/docs/gardener/shoot_operations/#force-deletion).

**Comment by pbochynski** [comment]
Yes - we can postpone this one. We should also check how Gardener handles the deletion of hibernated clusters. Maybe the force-deletion annotation will help to reduce the time.

**Comment by tobiscr** [comment]
We will for now not work on it, until we discovered how hibernation works. Possible that we can reuse this flag for deleting hibernated clusters faster.
