### ISSUE TITLE
Configure IMDS2 for AWS instances per default [KIM/feature]

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/infrastructure-manager#156]
**Description**

To increase the overall security of our AWS clusters, the default configuration in Gardener should be adjusted to use IMDS2 as default.

Currently, new worker pools are created having IMDS1 enabled (this is the default if not explicit configuration is provided). We have to adjust the shoot-spec for Gardener to use IMDS2 per default.

AC:
- [ ] Align with SREs on the rollout of this feature as it requires a migration of old AWS instances from IMDS1 to IMDS2
- [ ] All AWS clusters are using IMDS2 as default value, IMDS1 is no longer used

**Comment by tobiscr** [comment]
Impacts default configuration of worker pools - see also #46

**Comment by Disper** [comment]
- [related gardener announcement](https://listserv.sap.corp/pipermail/kubernetes-users/2024-March/001020.html)
- [gardener-extension-provider-aws docs's workerconfig section](https://github.com/gardener/gardener-extension-provider-aws/blob/master/docs/usage/usage.md#workerconfig)

**Comment by Disper** [comment]
Notes from today's alignment with @tobiscr and @ebensom 
At the end, we need to make sure that those two fields:
- `httpPutResponseHopLimit >=2`
- `httpTokens = "required"` 
will be configured for AWS for new clusters using a feature flag. SRE is willing to raise a PR with that change which @kyma-project/framefrog should review. Later, SRE will ensure that all shoots are upgraded to use those new values.

**Comment by tobiscr** [comment]
Fix for provisioner was created by @ebensom : https://github.com/kyma-project/control-plane/commit/ea75326a0e2f1108f4297dd04b8090cd75266898

**Comment by tobiscr** [comment]
Already covered in KIM
