### ISSUE TITLE
MVP: KIM can successfully create Gardener clusters on Azure, and AWS

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/infrastructure-manager#215]
**Description**

As next step of the migration from Provisioner to KIM we will support two Hyperscalers in KIM.

KIM will be able to produce two Hyperscaler specific Shoot-Specs  which are accepted by GArdener and can be used to successfully provision a Kubernetes cluster.

AC:
- [ ] KIM is able to produce working Shoot-Specs for two different Hyperscalers
    - [ ] Shoot-Spec is tested with Gardener and a Kubernetes cluster was successfully provisioned by Gardener
    - [ ] Shoot-Specs generated by KIM are compared with Shoot-Specs generated by Provisioner
    - [ ] Automated tests are implemented which verify the generate Shoot-Specs with a provided Shoot-Spec template

**Comment by akgalwas** [comment]
It was assumed we will support the following hyperscalers for MVP: AWS, and Azure
Assumptions:
- hyperscalers supported: AWS, Azure
- Runtime CR statuses are not important for now 

Workplan
- [x] [Prepare basic structures for converters](https://github.com/kyma-project/infrastructure-manager/pull/221)
- [ ] Add feature flag for enabling provisioning
- [ ] Add AWS provider specific config
- [ ] Add Azure provider specific config
- [ ] Implement controller that gets Runtime, and creates shoot CR. The controller should wait until the cluster is created. 
- [ ] Test cluster provisioning on DEV (apply CR, and verify the cluster created is fully functional) 

Stretch:
- [ ] Add the following configuration settings:
  - [ ]  Default Kubernetes version
  - [ ] DNS config (secret name, domain suffix (e.g dev.my.company.com), provider type name(e.g. aws-route53))
  - [ ] Provider config (`enableIMDSv2` for AWS)

**Comment by tobiscr** [comment]
Duplicate of #206
