### ISSUE TITLE
Migrate from GardenerCluster CR to KIM

### ISSUE THREAD

**Issue by Disper** [kyma-project/infrastructure-manager#251]
**Description**
- KEB should no longer create `Gardener Cluster`CRs
- KIM should create those CR
- (optional) Either now, or in a separate ticket change the name to a more meaningful name like `Kubeconfig`

**Reasons**
- KEB should no longer create `Gardener Cluster` CRs
- `Gardener Cluster` CR name is confusing in the current architecture as it is only responsible for managing kubeconfig secrets

**Attachments**
See https://github.com/kyma-project/infrastructure-manager/issues/187 for ideas

**Comment by tobiscr** [comment]
Duplicate of #282
