### ISSUE TITLE
KIM has to ensure that Assured Workloads are used for SKRs in KSA

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/infrastructure-manager#299]
**Description**

Caused by legal requirements is an adjustment for SKR clusters in SA required:

It has to be ensured, that all SKR clusters in this region are using assured workloads. This can be achieved by configuring the tolerations-field:

```
spec:
  tolerations:
    - key: ksa-assured-workload
```

We agreed with colleagues from KEB to set this field for each cluster which should be scheduled for CF-region "cf-sa30".

AC:
- [ ] KIM is setting the tolerations field is set in Shoot-spec for each cluster whcih gets scheduled in CF region `cf-sa30` (alternatively the BTP region `me-central2` could be used)

**Potential risk:**
The Gardener operator has to accept the toleration. This needs initially be configured by the Gardener team for this Gardener project.

**Reasons**

Being compliant with KSA restrictions for SKR clusters in SA.

**Attachments**

**Comment by tobiscr** [comment]
@varbanv :; do we have to support tolerations also for `me-central1` region? In the Gardener UI are two regions in ME supported. Currently, we focus only on `me-central2`. Should `me-central1` also use assured workloads?

**Comment by Disper** [comment]
@tobiscr FYI, #315 relies on having `me-central2` as a region
