### ISSUE TITLE
Making the processing more resilient

### ISSUE THREAD

**Issue by TorstenD-SAP** [kyma-project/infrastructure-manager#356]
**Description**

Making the processing of the Infrastructure Manager more resilient e. g by implementing a retry functionality

**Reasons**

KIM is performing critical changes on the SKR clusters and it has to be ensured, these changes are applied.

**Attachments**

**Comment by tobiscr** [comment]
@TorstenD-SAP : I was creating this issue for this task -  https://github.com/kyma-project/infrastructure-manager/issues/349. 

Can we close one of them as duplicate?

**Comment by TorstenD-SAP** [comment]
Duplicate (see https://github.com/kyma-project/infrastructure-manager/issues/356#issuecomment-2316921598)
