### ISSUE TITLE
[Threat Modeling] Improve secure configuration of KIM

### ISSUE THREAD

**Issue by TorstenD-SAP** [kyma-project/infrastructure-manager#357]
**Description**

Kubescape still reports some  miss-configurations. It has to be checked, if the secure configuration of KIM can be improved. Especially the following settings have to be checked:
- Container running as root ([Kubescape Control C-0013](https://hub.armosec.io/docs/c-0013))
- Secomp profile should be set to the default ([Kubescape Control C-0210](https://hub.armosec.io/docs/c-0210))
- To powerful permissions of the ServiceAccount used ([Kubescape Control C-0267](https://hub.armosec.io/docs/c-0267))

See also https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/f8cb6e55496b4bd1be68d6dfa4d15487.html?locale=en-US

**Reasons**

Reduce the attack surface

**Attachments**

**Comment by Disper** [comment]
> powerful permissions of the ServiceAccount used ([Kubescape Control C-0267](https://hub.armosec.io/docs/c-0267))
Related issue https://github.com/kyma-project/infrastructure-manager/issues/56

**Comment by Disper** [comment]
PRs:
(internal) - charts#2291
(internal) - charts#2288

**Comment by tobiscr** [comment]
> PRs: (internal) - charts#2295

and PR (internal) - mgt-plane-charts#2288

**Comment by Disper** [comment]
internal PR charts#2295 that is merged already included changes from #2288.
