### ISSUE TITLE
KIM supports flag for making the auditlog-configuration mandatory

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/infrastructure-manager#362]
**Description**

It's not allowed to handover a productive sKR cluster to customers without a properly configured auditlog. But this requirement is only for productive SKR clusters. For clusters created on our KCP DEV or STAGE landscape the usage of an auditlog instance is optional.

We will establish a configuration flag in KIM, which indicates whether the auditlog configuration is mandatory for created clusters. If it's mandatory and no auditlog instance could be found for the region of the requested cluster, the cluster creation process has to be stopped and status of the corresponding `RuntimeCR` has to be set to `ERROR`.

If the flag indicates that the auditlog configuration is optional, the cluster creation process will try to find an appropriate auditlog instance in the log. But if no auditlog instance is configured for the region of the requested cluster, the cluster creation process continues. The status of the `RuntimeCR` is not influenced by the missing auditlog configuration.

AC:
- [x] Establish a configuration flag (boolean) which indicates whether a proper auditlog configuration is mandatory for created SKR clusters.
    - [x] If flag indicates a mandatory auditlog configuration but no auditlog configuration could be found for the cluster region, the status of the corresponding `RuntimeCR` is set to `ERROR` and the cluster creation process stops
    - [x] If the indicates an optional auditlog configuration, the cluster creation process continues and the status of the `RuntimeCR` is not influenced.

**Reasons**

Ensure that productuve SKR clusters have always an auditlog instance configured.

**Attachments**

**Comment by Disper** [comment]
Implemented in #367, for example output please see [this](https://github.com/kyma-project/infrastructure-manager/issues/363#issuecomment-2338042285)

**Comment by mvshao** [comment]
The #367 is now merge with this feature. We can close this issue as resolved.
