### ISSUE TITLE
[QG] Simulate Cluster upgrade sceanrio in KIM with SREs (upgrade of K8s version and VM image version)

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/infrastructure-manager#408]
**Description**

As pre-requisite for a Go-Live, we have to ensure that KIM is properly dealing with an upgrade of 

* Kubernetes vesion
* VM image version

as we have to perform regularly updates on our SKR fleet.

AC:
- [x] Get in touch with SRE to align how their upgrade process for Kubernetes version and VM image version looks like 
- [x] Simulate a upgrade-scenario by upgrading an Shoot-Cluster via KIM
- [x] Prevent downgrades of machine image and kubernetes versions

**Reasons**

We have for beginning of Dec 2024 another SKR fleet upgrade scheduled and KIM has to be able to perform this upgrade properly

**Attachments**

**Comment by akgalwas** [comment]
Consider the following:
- When autoupdates are enabled we can be out of sync with Runtime CR (KEB is passing version)
- We need to implement a check that prevents from updating Kubernetes version when the version on Runtime CR is older. We should log some warning to the log, but still Runtime CR could be out of sync.

**Comment by akgalwas** [comment]
For now we need to prevent downgrades (we can use the Kubernetes version from the Runtime CR only if the version in the Runtime CR if greater than version on shoot)

**Comment by koala7659** [comment]
Related PR : https://github.com/kyma-project/infrastructure-manager/pull/483

**Comment by tobiscr** [comment]
Covered by https://github.tools.sap/kyma/backlog/issues/6177

@vvxxvvxx  - can you please confirm that you covered all the criterias mentioned in this issue above?

**Comment by vvxxvvxx** [comment]
Hi @tobiscr , performed a k8s version upgrade for a dev runtime, the test result [is described here](https://github.tools.sap/kyma/backlog/issues/6177#issuecomment-8769899). Could you please check? thanks.

**Comment by tobiscr** [comment]
Tested today the upgarde of image-version successfully. Findings are:

* https://github.com/kyma-project/infrastructure-manager/issues/537
* https://github.com/kyma-project/infrastructure-manager/issues/536
