### ISSUE TITLE
CI pipeline has to set `latest` tag to new generated KIM images

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/infrastructure-manager#415]
**Description**

To ensure the security scanners (BDBA) are using always the right image for their scans, we have to set the `latest` tag for each new created container image (https://github.com/kyma-project/infrastructure-manager/blob/main/sec-scanners-config.yaml#L3).

AC:
- [ ] For each new created KIM images, the pipelines also sets the `latest` tag for this new image

**Reasons**

Ensure Sec-Scanners are using correct image.

**Attachments**

**Comment by VOID404** [comment]
*For each new created KIM images **on default branch**
