### ISSUE TITLE
Infrastructure Manager - Prepare migration script/Go program that will create GardenerCluster for each existing cluster

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/infrastructure-manager#51]
**Description**

Prepare a Go program/script that will iterate over Kyma resources. For each Kyma resource it will:

1.  Read labels from  the Kyma resource
2. Create `GardenerCluster` CR

The `GardenerCluster` CR must contain the fields defined [here](https://github.com/kyma-project/infrastructure-manager/blob/main/config/samples/clusterinventory_v1_gardenercluster.yaml). Kyma resource is created by the KEB, and the labels it adds can be found [here](https://github.com/kyma-project/kyma-environment-broker/blob/7756a730c4bfba8da2cc552d07a3e5cbfba93d79/internal/process/steps/lifecycle_manager.go#L14). Mind that the [secret name](https://github.com/kyma-project/kyma-environment-broker/blob/7756a730c4bfba8da2cc552d07a3e5cbfba93d79/internal/process/steps/lifecycle_manager.go#L43) is also defined by KEB.

**Reasons**
In order to migrate to the architecture with the Infrastructure Manager responsible for dynamic kubeconfig creation the environment some additional steps must be performed. When Infrastructure Manager will be deployed on the target environment there will be a need to handle existent Kyma clusters.  The migration script is needed to make sure Infrastructure Manager will control all the runtimes.

**Comment by Disper** [comment]
The first version of go program running the migration already exists but is available in an internal repository. Feel free to reach me if you're interested in it.
