### ISSUE TITLE
[Threat Modeling] Assure that Connection is properly secured/encrypted

### ISSUE THREAD

**Issue by Disper** [kyma-project/infrastructure-manager#53]
**Acceptance Criteria**
- [ ]  Check TLS configuration of Gardener API
- [ ] Enforce strict certificate validation in the Infrastructure Manager

**Comment by mvshao** [comment]
Kyma Infrastructure Manager uses Gardener Kubeconfig to communicate with the Gardener API via an https protocol secured by a unique user and token. 
Infrastructure Manager does not use certificates to establish communication with external services.
