### ISSUE TITLE
KIM removes `shoot-oidc-service` extension for migrated clusters

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/infrastructure-manager#533]
**Description**

KIM removes `shoot-oidc-service` extension for migrated clusters.

**Expected result**

KIM shouldn't make substantial modifications to the shoot that was migrated.

**Actual result**

KIM removes `shoot-oidc-service` extension and as a result Gardener triggers reconciliation

**Steps to reproduce**

1. Pick a runtime that is controlled by the Provisioner, and was created with Migrator tool
2. Label the Runtime to be controled by KIM
 ```
kubectl label runtime/921ef1c6-5d50-413b-8b6b-f2f3ef13e79a  kyma-project.io/controlled-by-provisioner="false" -n kcp-system --overwrite
```
3. Observe the reconciliation is triggered, and `shoot-oidc-service` is missing.

**Troubleshooting**

The bug is in this [code](https://github.com/kyma-project/infrastructure-manager/blob/d75d9dfe86dd00d2138ae5825bd126bfd14a4c11/pkg/gardener/shoot/extender/oidc.go#L20).

**Comment by akgalwas** [comment]
Testing:
- [ ] DEV
  - [ ] Scenario with new cluster @koala7659 
    - [ ] Create new cluster
    - [ ] Update cluster and compare yamls before, and after 
    - [ ] Delete the cluster 
  - [ ] Scenario with migration @koala7659 
    - [ ] Use existing cluster created with KIM
    - [ ] Set it to be controlled by Provisioner
    - [ ] Run KIM on k3d cluster
    - [ ] Set the cluster to be controled by kim
    - [ ] Compare shoot yamls before, and after
- [ ] STAGE
  - [ ] Scenario with new cluster @m00g3n 
    - [ ] Create new cluster
    - [ ] Update cluster and compare yamls before, and after 
    - [ ] Delete the cluster  
  - [ ] Scenario with migration 1 @akgalwas @m00g3n 
    - [ ] Use existing cluster created with KIM
      - [ ] Set it to be controlled by Provisioner
      - [ ] Run KIM on k3d cluster
      - [ ] Set the cluster to be controled by kim
      - [ ] Compare shoot yamls before, and after  
   - [ ] Scenario with migration 2 @akgalwas 
      - [ ] Use existing cluster created with Provisioner
      - [ ] Set it to be controlled by Provisioner
      - [ ] Run KIM on k3d cluster
      - [ ] Set the cluster to be controled by kim
      - [ ] Compare shoot yamls before, and after

**Comment by Disper** [comment]
I believe there is an issue with `Shoot.Tolerations`. I've prepared a cluster that had in shoot spec the following list:

``` yaml
  tolerations:
    - key: ksa-assured-workload
    - key: seed.gardener.cloud/alpha-ha
```

KIM picked up the reconciliation, the conditions were set to be expected for our extender to set `ksa-assured-workload`. 
I expected to see:

``` yaml
  tolerations:
    - key: ksa-assured-workload
    - key: seed.gardener.cloud/alpha-ha
```

while I got:
``` yaml
  tolerations:
    - key: ksa-assured-workload
```

**Comment by zhoujing2022** [comment]
Defect was not fixed. here is the new bug issue: https://github.tools.sap/kyma/backlog/issues/6494
