### ISSUE TITLE
[Threat Modeling] Configure audit logs to track changes applied on CRs and secrets

### ISSUE THREAD

**Issue by Disper** [kyma-project/infrastructure-manager#55]
**Reason**
Those important IM resources should be audit logged.

**Acceptance Criteria**

Ensure following cases are recorded in the auditlog:

- [x] If an agent (app or a user) edits the GardenCluster CR - we should see an audit log of that action
- [x] If an agent (app or a user) edits the Runtime CR - we should see an audit log of that action
- [x] If an agent (app or a user) edits the secrets - we should see an audit log of that action
- [x] If an agent (app or a user) accesses gardener secret - we should see an audit log of that action
- [x] If the above does not happen, consult the situation with security experts and prepare the mitigation plan

**Comment by Disper** [comment]
Example list of logs:
<img width="333" alt="Pasted_Image_26_11_2024__14_57" src="https://github.com/user-attachments/assets/277621c0-ffed-45da-92f3-a4cbe1f5d7f1">

Example details:
<img width="1304" alt="Pasted_Image_26_11_2024__14_59" src="https://github.com/user-attachments/assets/1aa2507b-ba5a-44e2-a68d-ebd098bf6a6a">

While I did;t check the `accesses gardener secret ` part I don't see a reason why it should behave differently as with the regular secret checked.

@tobiscr is that enough?

**Comment by tobiscr** [comment]
Yes, if secrets are tracked also the gardener secret will be covered.
