### ISSUE TITLE
[Threat Modeling] Limit access to Gardener project kubeconfig

### ISSUE THREAD

**Issue by Disper** [kyma-project/infrastructure-manager#56]
**Reason**

We're using a kubeconfig defined in `gardener-kubeconfig-path`. We should limit the access to it to not allow unathorize access to the gardener project.

KIM has currently too many privileges and can also read other secrets which are not required for his work. This unnecessary privileges have to be removed to follow the least-privilege pattern.

**Acceptance criteria**
- [x] review access rights to the gardener project kubeconfig and adjust them to allow only read access for KIM and deny access to any other secret which is not relevant for KIM's regular work

**Comment by Disper** [comment]
#524 and #357 improved rbacs also around secrets.
KIM now can only work on secrets that are  in `kcp-system` namespace.
@tobiscr, would that be enough to consider this issue as mitigated?

**Comment by tobiscr** [comment]
Considering #531 we allow access only to secrets within the `kcp-system` namespace. As KIM has to update regularly secrets in this namespace (e.g. kubeconfigs of SKRs are also stored in secrets), being more restrictive would cause technical implications for KIM. 

Closing this issue as KIM has now limited access to secrets.

**Comment by tobiscr** [comment]
Waiting for merge of #531

**Comment by Disper** [comment]
#531 merged
