### ISSUE TITLE
[Threat Modeling] Restrict if possible the used http methods with the Gardener client

### ISSUE THREAD

**Issue by Disper** [kyma-project/infrastructure-manager#57]
**Description**
Allow only needed actions/http methods.

**Reason**
We don't want to provide a way to edit/delete cluster related data.

**Acceptance criteria**
- [x] Restrict if possible the used http methods with the Gardener client

**Attachments**
- https://github.com/gardener/gardener/blob/34df9b756dfb403aba117b4735580a97f44f55dc/docs/api-reference/authentication.md

**Comment by Disper** [comment]
We did not manage to restrict the usage of the HTTP method in the Gardener client, however, we believe that it's fine as
- we anyway have to create/update/delete the resources so use most HTTP methods 
- we have made some improvements as for https://github.com/kyma-project/infrastructure-manager/issues/357 including improving RBACs which also serves the purpose of restricting the unwanted usage.

**Comment by Disper** [comment]
@tobiscr , @TorstenD-SAP - is that acceptable?

**Comment by tobiscr** [comment]
From my side it's acceptable - restricting HTTP methods would probably require a custom HTTP client on our side which is causing new challenges (not using well-tested libraries can cause new problems). I would for now take the risk to have an HTTP client with support of all HTTP-methods in place instead using a custom imlementation.

Alternatively, we could think to restrict the service-account we use for communicating with Gardener's seed-cluster to limit it's permissions on the API-server side.
