### ISSUE TITLE
Infrastructure Manager - create initial project structure

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/infrastructure-manager#9]
**Description**

Create a minimal structure for ~Cluster Inventory~ Infrastructure Manager.

Acceptance criteria:
- [x] Initial project scaffolding - @Disper 
  - [x] #12 
  - [x] #15
  - [x] #20
- [x] https://github.com/kyma-project/cluster-inventory/pull/16 - @Disper 
- [x] #17 - @Disper 
- [x] #21 - @Disper 
- [x] https://github.com/kyma-project/test-infra/pull/8877 - @Disper 
- [x] #24 - @akgalwas 
- ~Simple controller implemented. It should print CR name, when a CR is created, or deleted.~
- [x] Controller can be deployed with `make deploy` command - @akgalwas 
- [x] renaming the project to the final name
  - https://github.com/kyma-project/test-infra/pull/8894
  - #29

Stretch:

- consider a /hack directory with convenient Makefiles for local/ci 
- [x] #7 
- Security scans
  - Also consider new go lang vuln check
- [x] #25
- reuse compliance
- Consider e2e smoke test
- markdown link checker

**Reasons**

In order to kick off the implementation we need to define the code structure, create pipelines. We also need to define the interface for Kyma Environment Broker that is supposed to create Cluster CRs.

**Comment by Disper** [comment]
Stretches created as follow-ups:
- https://github.com/kyma-project/infrastructure-manager/issues/34
